import type { Asset } from '@/types/library';

export const assets: Asset[] = [
  {
    id: 'kpi-001',
    name: 'Revenue per User',
    description: 'Average revenue generated per active user across all business segments and affiliates.',
    type: 'kpi',
    date: '2024-06-15',
    featured: true,
    trending: true,
    businessQuestions: [
      'How much revenue does each active user generate on average?',
      'How does RPU vary across customer segments?',
      'What is the YoY trend in RPU by affiliate?',
    ],
    metricIds: ['M-0042', 'M-0043', 'M-0044'],
    calculation: 'Total Revenue ÷ Monthly Active Users',
    visuals: ['Line Chart', 'Bar Chart', 'KPI Card', 'Heat Map'],
    affiliateApplicability: ['US', 'EMEA', 'APAC', 'LATAM'],
  },
  {
    id: 'kpi-002',
    name: 'Churn Rate',
    description: 'Percentage of customers who discontinued the service over a rolling 30-day period.',
    type: 'kpi',
    date: '2024-06-20',
    featured: true,
    businessQuestions: [
      'What percentage of customers churn each month?',
      'Which segments carry the highest churn risk?',
      'How does churn correlate with onboarding completion?',
    ],
    metricIds: ['M-0078', 'M-0079'],
    calculation: '(Customers Lost in Period ÷ Customers at Start of Period) × 100',
    visuals: ['Line Chart', 'Funnel', 'Cohort Grid'],
    affiliateApplicability: ['US', 'EMEA', 'APAC'],
  },
  {
    id: 'kpi-003',
    name: 'Customer Acquisition Cost',
    description: 'Total blended cost to acquire one new paying customer, inclusive of all sales and marketing spend.',
    type: 'kpi',
    date: '2024-05-30',
    featured: true,
    businessQuestions: [
      'What is the average cost to acquire a new customer?',
      'How does CAC compare to LTV by acquisition channel?',
    ],
    metricIds: ['M-0055', 'M-0056'],
    calculation: 'Total Sales & Marketing Spend ÷ New Customers Acquired',
    visuals: ['Bar Chart', 'KPI Card', 'Scatter Plot'],
    affiliateApplicability: ['US', 'EMEA'],
  },
  {
    id: 'kpi-004',
    name: 'Net Promoter Score',
    description: 'Customer loyalty indicator derived from the standard 0-10 recommendation survey.',
    type: 'kpi',
    date: '2024-07-10',
    businessQuestions: [
      'How likely are customers to recommend our product?',
      'How does NPS trend quarter over quarter?',
      'Which affiliate has the strongest advocacy base?',
    ],
    metricIds: ['M-0091', 'M-0092'],
    calculation: '% Promoters (score 9–10) − % Detractors (score 0–6)',
    visuals: ['Gauge', 'Trend Line', 'Bar Chart'],
    affiliateApplicability: ['US', 'EMEA', 'APAC', 'LATAM', 'CA'],
  },
  {
    id: 'kpi-005',
    name: 'Monthly Active Users',
    description: 'Count of unique users who triggered at least one tracked event within the last 30 calendar days.',
    type: 'kpi',
    date: '2024-06-05',
    trending: true,
    businessQuestions: [
      'How many users are actively engaging with the platform each month?',
      'What is the WAU/MAU stickiness ratio?',
    ],
    metricIds: ['M-0011', 'M-0012'],
    calculation: 'DISTINCT(user_id) WHERE last_active_at >= CURRENT_DATE − 30',
    visuals: ['Line Chart', 'KPI Card', 'Area Chart'],
    affiliateApplicability: ['US', 'EMEA', 'APAC', 'LATAM'],
  },
  {
    id: 'story-001',
    name: 'EBITDA Storyboard',
    description: 'End-to-end narrative of EBITDA drivers, cost levers, and margin improvement opportunities by BU.',
    type: 'storyboard',
    date: '2024-06-01',
    featured: true,
    coupledKpis: ['Revenue per User', 'Operating Cost Ratio', 'Gross Margin'],
    coupledFilters: ['Business Unit', 'Time Period', 'Region'],
    applicableAffiliates: ['US', 'EMEA', 'APAC'],
    requiresAccess: true,
  },
  {
    id: 'story-002',
    name: 'Q2 Growth Analysis',
    description: 'Quarterly growth storyboard covering acquisition, retention velocity, and expansion revenue trends.',
    type: 'storyboard',
    date: '2024-07-05',
    trending: true,
    coupledKpis: ['Revenue per User', 'Churn Rate', 'Monthly Active Users'],
    coupledFilters: ['Quarter', 'Segment', 'Acquisition Channel'],
    applicableAffiliates: ['US', 'EMEA'],
    requiresAccess: false,
  },
  {
    id: 'story-003',
    name: 'Customer Journey Board',
    description: 'Full-funnel storyboard from first touch through retention, with drop-off diagnostics at each stage.',
    type: 'storyboard',
    date: '2024-05-20',
    featured: true,
    coupledKpis: ['CAC', 'NPS', 'Churn Rate', 'LTV'],
    coupledFilters: ['Cohort', 'Channel', 'Affiliate'],
    applicableAffiliates: ['US', 'CA', 'EMEA'],
    requiresAccess: true,
  },
  {
    id: 'layout-001',
    name: 'Executive Summary Layout',
    description: 'Board-ready layout for monthly business reviews. Optimized for C-suite consumption — minimal, high-signal.',
    type: 'layout',
    date: '2024-06-12',
    featured: true,
    pageCount: 3,
    kpisUsed: ['Revenue per User', 'Churn Rate', 'MAU', 'NPS'],
  },
  {
    id: 'layout-002',
    name: 'Regional Performance View',
    description: 'Side-by-side multi-region comparison layout with KPI panels and geographic breakdown sections.',
    type: 'layout',
    date: '2024-06-25',
    pageCount: 5,
    kpisUsed: ['Revenue per User', 'CAC', 'MAU'],
  },
  {
    id: 'viz-001',
    name: 'Revenue Trend Chart',
    description: 'Interactive line chart visualizing MoM and YoY revenue trends with 90-day forecast bands.',
    type: 'dataviz',
    date: '2024-07-01',
    featured: true,
    trending: true,
    relatedKpis: ['Revenue per User', 'ARPU'],
    chartType: 'Line + Forecast Band',
  },
  {
    id: 'viz-002',
    name: 'Cohort Retention Matrix',
    description: 'Heatmap of user retention rates by weekly acquisition cohort. Covers weeks 1–12 post-signup.',
    type: 'dataviz',
    date: '2024-07-08',
    relatedKpis: ['Churn Rate', 'Monthly Active Users'],
    chartType: 'Heat Map',
  },
];
